name             "letsencrypt"
maintainer       "Sebastian Johnsson"
maintainer_email "sebastian.johnsson@gmail.com"
license          "Apache 2.0"
description      "Configures Let's Encrypt SSL certificates."
version          "0.1"
